apiVersion: v1
kind: Namespace
metadata:
  name: kubebigbrother
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubebigbrother
  namespace: kubebigbrother
  labels:
    app: kubebigbrother
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubebigbrother-as-admin
  labels:
    app: kubebigbrother
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubebigbrother
  namespace: kubebigbrother