db-dialect: sqlite # database dialect
db-args: tmp/kubebigbrother.sqlite # database args
env: debug # environment (environments with special meaning: [debug])
kubeconfig: /path/to/kubeconfig # path to kubeconfig
