channels: # define channels
  print-to-stdout: # channel name
    type: print # channel type
    print: # configuration for type: print
      writer: stdout # writer, currently supported options: [stdout]

namespaces: # defines resources to watch
- namespace: "demo" # namespace in kubernetes, "" means all namespaces
  resources: # defines resources in this namespace
  - name: "demo-configmaps" # unique name
    resource: "configmaps" # resource name in kubernetes
    noticeWhenAdded: true # record event when resource added
    noticeWhenDeleted: true # record event when resource deleted
    noticeWhenUpdated: true # record event when resource updated
    updateOn: # specify fields to watch modification
    - ".data"
    channelNames: # channel names only for this resource, optional
    - print-to-stdout